export const dashboardPages = {
  dashboard: {
    title: "My Dashboard",
    subtitle: "View your work updates, leave summary, payslip status, and documents.",
    action: "View profile",
    stats: [
      { label: "Leave balance", value: "42", change: "Days" },
      { label: "My requests", value: "3", change: "Open" },
      { label: "Payslip status", value: "Ready", change: "May" },
      { label: "Documents", value: "5", change: "Filed" },
    ],
    primaryTitle: "My work snapshot",
    primaryText: "A simple overview of your personal employee information and pending items.",
    tableTitle: "My recent items",
    tableColumns: ["Item", "Category", "Date", "Status"],
    tableRows: [
      ["Annual leave request", "Leave", "Today", "Pending"],
      ["Monthly payslip", "Payroll", "May 10", "Ready"],
      ["Profile update", "Account", "This week", "Open"],
    ],
    sideTitle: "My next actions",
    sideItems: [
      { title: "Check leave balance", text: "Review available Sick, Casual, and Annual leave." },
      { title: "Download payslip", text: "Save your latest monthly salary slip." },
      { title: "Update profile", text: "Keep your personal details current." },
    ],
  },
  people: {
    title: "Team",
    subtitle: "View your team members, departments, and basic work contacts.",
    action: "View team",
    stats: [
      { label: "Team members", value: "12", change: "Active" },
      { label: "Department", value: "Design", change: "Team" },
      { label: "Manager", value: "1", change: "Assigned" },
      { label: "Profile complete", value: "88%", change: "+6%" },
    ],
    primaryTitle: "Team directory",
    primaryText: "Find basic team information and work roles for everyday coordination.",
    tableTitle: "Team contacts",
    tableColumns: ["Name", "Department", "Role", "Status"],
    tableRows: [
      ["Ayesha Khan", "Design", "Product Designer", "Active"],
      ["Bilal Ahmed", "Engineering", "Frontend Developer", "Active"],
      ["Sara Malik", "Finance", "Payroll Officer", "Onboarding"],
    ],
    sideTitle: "Team notes",
    sideItems: [
      { title: "Know your department", text: "Check your team and reporting information." },
      { title: "Keep contacts current", text: "Update your own phone and address details." },
      { title: "View coworkers", text: "Quickly find names and roles in your team." },
    ],
  },
  payslip: {
    title: "Payslips",
    subtitle: "View your salary slips, deductions, reimbursements, and monthly pay status.",
    action: "Download",
    stats: [
      { label: "Payroll month", value: "May", change: "Open" },
      { label: "Gross pay", value: "$1.8k", change: "May" },
      { label: "Deductions", value: "$120", change: "Checked" },
      { label: "Payslips", value: "12", change: "Year" },
    ],
    primaryTitle: "My payslip",
    primaryText: "Review your monthly salary details and payroll status.",
    tableTitle: "My payroll items",
    tableColumns: ["Month", "Gross", "Deduction", "Status"],
    tableRows: [
      ["May", "$1,850", "$120", "Ready"],
      ["April", "$1,850", "$110", "Paid"],
      ["March", "$1,800", "$105", "Paid"],
    ],
    sideTitle: "Payslip notes",
    sideItems: [
      { title: "Check deductions", text: "Review tax and other monthly deductions." },
      { title: "View reimbursements", text: "Confirm any approved additions." },
      { title: "Download slip", text: "Save your latest payslip record." },
    ],
  },
  benefited: {
    title: "Benefits",
    subtitle: "View your allowances, insurance, leave balance, and benefit enrollment.",
    action: "View details",
    stats: [
      { label: "My benefits", value: "4", change: "Active" },
      { label: "Pending items", value: "1", change: "Review" },
      { label: "Allowance", value: "$120", change: "Month" },
      { label: "Coverage", value: "Active", change: "Valid" },
    ],
    primaryTitle: "My benefits overview",
    primaryText: "See which benefits and allowances are connected to your employee account.",
    tableTitle: "My benefit enrollments",
    tableColumns: ["Benefit", "Value", "Renewal", "Status"],
    tableRows: [
      ["Health insurance", "Covered", "Jun 01", "Active"],
      ["Transport allowance", "$80", "Monthly", "Active"],
      ["Meal subsidy", "$40", "Monthly", "Review"],
    ],
    sideTitle: "Benefit notes",
    sideItems: [
      { title: "Check eligibility", text: "Review benefits available to your role." },
      { title: "Track renewal", text: "Keep an eye on insurance renewal dates." },
      { title: "Review allowances", text: "Check your monthly allowance details." },
    ],
  },
  performance: {
    title: "Performance",
    subtitle: "View your goals, feedback cycle, ratings, and check-ins.",
    action: "View goals",
    stats: [
      { label: "Review cycle", value: "Q2", change: "Live" },
      { label: "Completed", value: "73%", change: "+18%" },
      { label: "My goals", value: "4", change: "Open" },
      { label: "Check-ins", value: "2", change: "This month" },
    ],
    primaryTitle: "My performance cycle",
    primaryText: "Track your review progress, goals, and feedback items.",
    tableTitle: "My review progress",
    tableColumns: ["Goal", "Owner", "Review", "Status"],
    tableRows: [
      ["Improve delivery", "Me", "Q2 Review", "Submitted"],
      ["Skill growth", "Me", "Q2 Review", "Draft"],
      ["Goal check", "Manager", "Monthly", "Scheduled"],
    ],
    sideTitle: "Review notes",
    sideItems: [
      { title: "Update goals", text: "Keep your progress notes current." },
      { title: "Prepare feedback", text: "Add examples before your review." },
      { title: "Read summary", text: "Check final review outcomes when shared." },
    ],
  },
  personalDetails: {
    title: "Personal Details",
    subtitle: "View and update your personal, contact, emergency, and identity information.",
    action: "Update info",
    stats: [
      { label: "Profile status", value: "92%", change: "+7%" },
      { label: "Missing fields", value: "5", change: "-2" },
      { label: "Documents", value: "12", change: "Filed" },
      { label: "Emergency contacts", value: "2", change: "Current" },
    ],
    primaryTitle: "Employee profile",
    primaryText: "Keep your employee information accurate for payroll, documents, and support.",
    tableTitle: "My profile fields",
    tableColumns: ["Section", "Value", "Last updated", "Status"],
    tableRows: [
      ["Contact", "Phone and email", "May 02", "Complete"],
      ["Address", "Primary residence", "Apr 18", "Review"],
      ["Identity", "CNIC and tax ID", "Mar 29", "Complete"],
    ],
    sideTitle: "Profile notes",
    sideItems: [
      { title: "Review address", text: "Confirm current residence details." },
      { title: "Update contact", text: "Add alternate phone number." },
      { title: "File identity docs", text: "Check uploaded document quality." },
    ],
  },
  jobReferences: {
    title: "Job & References",
    subtitle: "View your employment details, role information, and reference records.",
    action: "View details",
    stats: [
      { label: "References", value: "2", change: "Saved" },
      { label: "Verified", value: "1", change: "Done" },
      { label: "Open checks", value: "1", change: "Pending" },
      { label: "Role record", value: "Current", change: "Active" },
    ],
    primaryTitle: "My job information",
    primaryText: "Keep your work history and reference information visible in one place.",
    tableTitle: "My reference checks",
    tableColumns: ["Record", "Reference", "Company", "Status"],
    tableRows: [
      ["Current role", "M. Farooq", "WaveSpace", "Verified"],
      ["Previous role", "H. Saeed", "NorthLabs", "Pending"],
      ["Internship", "R. Iqbal", "LedgerPro", "Verified"],
    ],
    sideTitle: "Job notes",
    sideItems: [
      { title: "Review role details", text: "Check your designation and department." },
      { title: "Update references", text: "Keep reference contact details current." },
      { title: "Confirm job history", text: "Match dates with your employee record." },
    ],
  },
  document: {
    title: "Documents",
    subtitle: "View your contracts, identity files, payslips, and employee letters.",
    action: "Upload file",
    stats: [
      { label: "My files", value: "12", change: "Saved" },
      { label: "Pending review", value: "1", change: "Open" },
      { label: "Expiring soon", value: "1", change: "Alert" },
      { label: "Signed", value: "97%", change: "Done" },
    ],
    primaryTitle: "My document center",
    primaryText: "Keep your employee documents organized and easy to access.",
    tableTitle: "My recent documents",
    tableColumns: ["Document", "Owner", "Date", "Status"],
    tableRows: [
      ["Employment contract", "Me", "May 01", "Signed"],
      ["CNIC copy", "Me", "Apr 26", "Review"],
      ["Salary certificate", "Me", "Apr 20", "Issued"],
    ],
    sideTitle: "Document notes",
    sideItems: [
      { title: "Check uploads", text: "Make sure your identity files are readable." },
      { title: "Check expiries", text: "Renew documents before the due date." },
      { title: "Download records", text: "Save important employee letters." },
    ],
  },
  settings: {
    title: "Settings",
    subtitle: "Manage your account preferences, notifications, and leave settings.",
    action: "Save changes",
    stats: [
      { label: "Account", value: "Active", change: "Ready" },
      { label: "Leave allowance", value: "42", change: "Days" },
      { label: "Notifications", value: "8", change: "On" },
      { label: "Security", value: "Good", change: "Checked" },
    ],
    primaryTitle: "My settings",
    primaryText: "Adjust the basic preferences used in your employee portal.",
    tableTitle: "My configuration",
    tableColumns: ["Setting", "Value", "Owner", "Status"],
    tableRows: [
      ["Leave limits", "42 days yearly", "System", "Active"],
      ["Payroll currency", "USD", "Payroll", "Active"],
      ["Session length", "1 hour", "Account", "Active"],
    ],
    sideTitle: "Settings notes",
    sideItems: [
      { title: "Review leave rules", text: "Know your yearly leave allowance." },
      { title: "Check account", text: "Confirm your profile access is working." },
      { title: "Manage notifications", text: "Check email and app alerts." },
    ],
  },
  support: {
    title: "Support",
    subtitle: "Create and track your help requests for leave, payroll, documents, and access.",
    action: "Create ticket",
    stats: [
      { label: "Open tickets", value: "6", change: "-2" },
      { label: "Avg response", value: "2h", change: "Fast" },
      { label: "Resolved", value: "34", change: "+9" },
      { label: "Satisfaction", value: "94%", change: "+4%" },
    ],
    primaryTitle: "Support desk",
    primaryText: "Keep employee questions visible and route requests to the right owner.",
    tableTitle: "Recent tickets",
    tableColumns: ["Ticket", "Requester", "Priority", "Status"],
    tableRows: [
      ["Payslip correction", "Ayesha Khan", "High", "Open"],
      ["Leave balance issue", "Bilal Ahmed", "Medium", "Review"],
      ["Document upload", "Sara Malik", "Low", "Resolved"],
    ],
    sideTitle: "Support tasks",
    sideItems: [
      { title: "Respond to high priority", text: "Handle payroll ticket first." },
      { title: "Resolve leave issue", text: "Check policy balance calculation." },
      { title: "Update help notes", text: "Keep common answers current." },
    ],
  },
};
