export const dashboardPages = {
  dashboard: {
    title: "Dashboard",
    subtitle: "Track workforce activity, leave usage, and payroll readiness.",
    action: "New report",
    stats: [
      { label: "Active employees", value: "128", change: "+8" },
      { label: "Open leave requests", value: "14", change: "Today" },
      { label: "Payroll ready", value: "96%", change: "+4%" },
      { label: "Documents pending", value: "7", change: "-3" },
    ],
    primaryTitle: "Today at a glance",
    primaryText: "A quick operational view of the items HR needs to review before the day closes.",
    tableTitle: "Priority queue",
    tableColumns: ["Item", "Owner", "Due", "Status"],
    tableRows: [
      ["Annual leave approval", "HR Admin", "Today", "Review"],
      ["Payslip batch", "Finance", "May 10", "Ready"],
      ["Profile updates", "People Ops", "This week", "Open"],
    ],
    sideTitle: "Next actions",
    sideItems: [
      { title: "Review leave balance", text: "Check requests that affect monthly limits." },
      { title: "Confirm payroll inputs", text: "Verify deductions before export." },
      { title: "Update employee files", text: "Collect missing personal documents." },
    ],
  },
  people: {
    title: "People",
    subtitle: "Manage employee records, teams, roles, and onboarding status.",
    action: "Add person",
    stats: [
      { label: "Total people", value: "128", change: "+5" },
      { label: "Onboarding", value: "9", change: "Active" },
      { label: "Departments", value: "6", change: "+1" },
      { label: "Profile complete", value: "88%", change: "+6%" },
    ],
    primaryTitle: "Employee directory",
    primaryText: "Keep core employee records consistent so leave, payroll, and documents stay connected.",
    tableTitle: "Recently updated employees",
    tableColumns: ["Name", "Department", "Role", "Status"],
    tableRows: [
      ["Ayesha Khan", "People", "HR Executive", "Active"],
      ["Bilal Ahmed", "Engineering", "Frontend Developer", "Active"],
      ["Sara Malik", "Finance", "Payroll Officer", "Onboarding"],
    ],
    sideTitle: "People tasks",
    sideItems: [
      { title: "Verify new joiners", text: "Confirm documents and joining dates." },
      { title: "Review departments", text: "Keep reporting lines accurate." },
      { title: "Profile cleanup", text: "Resolve missing phone and address fields." },
    ],
  },
  payslip: {
    title: "Payslips",
    subtitle: "Prepare salary slips, deductions, reimbursements, and monthly exports.",
    action: "Run payroll",
    stats: [
      { label: "Payroll month", value: "May", change: "Open" },
      { label: "Gross payroll", value: "$84k", change: "+3%" },
      { label: "Deductions", value: "$9.2k", change: "Checked" },
      { label: "Ready slips", value: "121", change: "+12" },
    ],
    primaryTitle: "Payroll preparation",
    primaryText: "Review pending adjustments before generating employee salary slips.",
    tableTitle: "Payroll items",
    tableColumns: ["Employee", "Gross", "Deduction", "Status"],
    tableRows: [
      ["Ayesha Khan", "$1,850", "$120", "Ready"],
      ["Bilal Ahmed", "$2,200", "$90", "Draft"],
      ["Sara Malik", "$1,650", "$110", "Ready"],
    ],
    sideTitle: "Payroll checklist",
    sideItems: [
      { title: "Confirm attendance", text: "Sync leave deductions before payroll." },
      { title: "Review bonuses", text: "Approve one-time additions." },
      { title: "Export batch", text: "Download final payroll file." },
    ],
  },
  benefited: {
    title: "Benefits",
    subtitle: "Track allowances, insurance, leave balances, and employee benefit enrollment.",
    action: "Add benefit",
    stats: [
      { label: "Enrolled", value: "116", change: "+4" },
      { label: "Pending review", value: "8", change: "Today" },
      { label: "Monthly cost", value: "$12k", change: "+2%" },
      { label: "Coverage rate", value: "91%", change: "+5%" },
    ],
    primaryTitle: "Benefits overview",
    primaryText: "Monitor benefit eligibility and enrollment from one operational dashboard.",
    tableTitle: "Benefit enrollments",
    tableColumns: ["Benefit", "Employees", "Renewal", "Status"],
    tableRows: [
      ["Health insurance", "104", "Jun 01", "Active"],
      ["Transport allowance", "78", "Monthly", "Active"],
      ["Meal subsidy", "92", "Monthly", "Review"],
    ],
    sideTitle: "Benefit tasks",
    sideItems: [
      { title: "Validate eligibility", text: "Review pending employee enrollments." },
      { title: "Renew coverage", text: "Prepare insurance renewal list." },
      { title: "Audit allowances", text: "Check duplicate benefit claims." },
    ],
  },
  performance: {
    title: "Performance",
    subtitle: "Review goals, feedback cycles, ratings, and manager check-ins.",
    action: "Start review",
    stats: [
      { label: "Review cycle", value: "Q2", change: "Live" },
      { label: "Completed", value: "73%", change: "+18%" },
      { label: "Goals open", value: "42", change: "-6" },
      { label: "Check-ins", value: "31", change: "This week" },
    ],
    primaryTitle: "Performance cycle",
    primaryText: "Keep reviews moving with clear ownership across employees and managers.",
    tableTitle: "Review progress",
    tableColumns: ["Employee", "Manager", "Review", "Status"],
    tableRows: [
      ["Ayesha Khan", "Omar Ali", "Q2 Review", "Submitted"],
      ["Bilal Ahmed", "Nida Raza", "Q2 Review", "Draft"],
      ["Sara Malik", "Omar Ali", "Goal check", "Scheduled"],
    ],
    sideTitle: "Review tasks",
    sideItems: [
      { title: "Collect manager notes", text: "Send reminders for pending reviews." },
      { title: "Calibrate ratings", text: "Compare team scoring patterns." },
      { title: "Publish summaries", text: "Share final review outcomes." },
    ],
  },
  personalDetails: {
    title: "Personal Details",
    subtitle: "Maintain personal, contact, emergency, and identity information.",
    action: "Update info",
    stats: [
      { label: "Profile status", value: "92%", change: "+7%" },
      { label: "Missing fields", value: "5", change: "-2" },
      { label: "Documents", value: "12", change: "Filed" },
      { label: "Emergency contacts", value: "2", change: "Current" },
    ],
    primaryTitle: "Employee profile",
    primaryText: "Keep employee information accurate for HR records, payroll, and compliance workflows.",
    tableTitle: "Profile fields",
    tableColumns: ["Section", "Value", "Last updated", "Status"],
    tableRows: [
      ["Contact", "Phone and email", "May 02", "Complete"],
      ["Address", "Primary residence", "Apr 18", "Review"],
      ["Identity", "CNIC and tax ID", "Mar 29", "Complete"],
    ],
    sideTitle: "Profile tasks",
    sideItems: [
      { title: "Review address", text: "Confirm current residence details." },
      { title: "Update contact", text: "Add alternate phone number." },
      { title: "File identity docs", text: "Check uploaded document quality." },
    ],
  },
  jobReferences: {
    title: "Job & References",
    subtitle: "Track employment history, reference checks, and role records.",
    action: "Add reference",
    stats: [
      { label: "References", value: "18", change: "+3" },
      { label: "Verified", value: "12", change: "+2" },
      { label: "Open checks", value: "6", change: "Pending" },
      { label: "Role records", value: "24", change: "Current" },
    ],
    primaryTitle: "Reference tracking",
    primaryText: "Organize employment references and job history for hiring and internal HR files.",
    tableTitle: "Reference checks",
    tableColumns: ["Candidate", "Reference", "Company", "Status"],
    tableRows: [
      ["Ayesha Khan", "M. Farooq", "WaveSpace", "Verified"],
      ["Bilal Ahmed", "H. Saeed", "NorthLabs", "Pending"],
      ["Sara Malik", "R. Iqbal", "LedgerPro", "Verified"],
    ],
    sideTitle: "Reference tasks",
    sideItems: [
      { title: "Call pending contacts", text: "Follow up on open verifications." },
      { title: "Attach notes", text: "Save reference summaries." },
      { title: "Confirm job history", text: "Match dates with employee records." },
    ],
  },
  document: {
    title: "Documents",
    subtitle: "Store contracts, identity files, payslips, and HR letters.",
    action: "Upload file",
    stats: [
      { label: "Total files", value: "312", change: "+21" },
      { label: "Pending review", value: "11", change: "-4" },
      { label: "Expiring soon", value: "3", change: "Alert" },
      { label: "Signed", value: "97%", change: "+2%" },
    ],
    primaryTitle: "Document center",
    primaryText: "Keep employee documents searchable, organized, and ready for audits.",
    tableTitle: "Recent documents",
    tableColumns: ["Document", "Owner", "Date", "Status"],
    tableRows: [
      ["Employment contract", "Ayesha Khan", "May 01", "Signed"],
      ["CNIC copy", "Bilal Ahmed", "Apr 26", "Review"],
      ["Salary certificate", "Sara Malik", "Apr 20", "Issued"],
    ],
    sideTitle: "Document tasks",
    sideItems: [
      { title: "Review uploads", text: "Approve pending identity files." },
      { title: "Check expiries", text: "Renew documents before due date." },
      { title: "Export archive", text: "Prepare monthly HR record backup." },
    ],
  },
  settings: {
    title: "Settings",
    subtitle: "Configure company preferences, security, notifications, and HR rules.",
    action: "Save changes",
    stats: [
      { label: "Admins", value: "4", change: "Active" },
      { label: "Leave rules", value: "3", change: "Set" },
      { label: "Notifications", value: "8", change: "On" },
      { label: "Security", value: "Good", change: "Checked" },
    ],
    primaryTitle: "Workspace settings",
    primaryText: "Control the defaults that keep HR workflows consistent across the app.",
    tableTitle: "Configuration",
    tableColumns: ["Setting", "Value", "Owner", "Status"],
    tableRows: [
      ["Leave limits", "42 days yearly", "HR Admin", "Active"],
      ["Payroll currency", "USD", "Finance", "Active"],
      ["Session length", "1 hour", "Admin", "Active"],
    ],
    sideTitle: "Settings tasks",
    sideItems: [
      { title: "Review leave rules", text: "Keep policy limits aligned with HR." },
      { title: "Manage admins", text: "Confirm access for trusted users." },
      { title: "Audit notifications", text: "Check email and app alerts." },
    ],
  },
  support: {
    title: "Support",
    subtitle: "Track help requests, product issues, and employee support tickets.",
    action: "Create ticket",
    stats: [
      { label: "Open tickets", value: "6", change: "-2" },
      { label: "Avg response", value: "2h", change: "Fast" },
      { label: "Resolved", value: "34", change: "+9" },
      { label: "Satisfaction", value: "94%", change: "+4%" },
    ],
    primaryTitle: "Support desk",
    primaryText: "Keep employee questions visible and route requests to the right owner.",
    tableTitle: "Recent tickets",
    tableColumns: ["Ticket", "Requester", "Priority", "Status"],
    tableRows: [
      ["Payslip correction", "Ayesha Khan", "High", "Open"],
      ["Leave balance issue", "Bilal Ahmed", "Medium", "Review"],
      ["Document upload", "Sara Malik", "Low", "Resolved"],
    ],
    sideTitle: "Support tasks",
    sideItems: [
      { title: "Respond to high priority", text: "Handle payroll ticket first." },
      { title: "Resolve leave issue", text: "Check policy balance calculation." },
      { title: "Update help notes", text: "Keep common answers current." },
    ],
  },
};
